apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: gnl-knowledge-graph
  labels:
    app: gnl-api
spec:
  selector:
    app: gnl-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP